### ISSUE TITLE
unzipped folder

### ISSUE THREAD

**Issue by ShanEllis** [Liuyi616/My-Grimm-bot#1]
Hi! You want the unzipped folder here, so that when people visit your repo, they can see the files you have/code you've written.

**Comment by Liuyi616** [comment]
> Hi! You want the unzipped folder here, so that when people visit your repo, they can see the files you have/code you've written.

Hi Ellis! Thank you for reminding me! So now I need to resubmit an unzipped folder and delete the compressed files, right?

**Comment by ShanEllis** [comment]
Yup - looks good now!
